services:
  mongo:
    image: mongo:latest
    container_name: crm-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: crm-api
    volumes:
      - mongo-data:/data/db

  app:
    container_name: crm-api
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - mongo

volumes:
  mongo-data:
