spring:
  data:
    mongodb:
      uri: ${MONGODB_DATABASE_URL:mongodb://localhost:27018/crm-api}
      auto-index-creation: true
      uuid-representation: standard
  docker:
    compose:
      lifecycle-management: start-only
error:
  handling:
    http-status-in-json-response: true
    exception-logging: NO_LOGGING
    full-stacktrace-http-statuses: 5xx
    log-levels:
      5xx: ERROR
springdoc:
  swagger-ui:
    path: /swagger-ui
  pathsToMatch: /api/**
